version: "3.9"
services:
    server1:
        build: .
        ports:
        - "8080:8080"
        environment:
            PORT: 8080
            REMOTE_SERVICE: server2:8080
    server2:
        build: .
        ports:
        - "8081:8080"
        environment:
            PORT: 8080
