---
apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
metadata:
  name: xxc-demo
  namespace: xcc-dns
  annotations:
    connectivity.tanzu.vmware.com/dns-hostname: '*.xcc.test'
addressType: FQDN
endpoints:
  - addresses:
    - "xxc-demo.apps.dev.eduk8s.io"
