#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Namespace
metadata:
  name: xcc-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcc-demo
  namespace: xcc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xcc-demo
  template:
    metadata:
      labels:
        app: xcc-demo
    spec:
      containers:
      - name: xcc-demo
        image: docker.io/jorgemoralespou/xcc-demo-sample-app:latest
        env:
        - name: PORT
          value: "8080"
        - name: REMOTE_SERVICE
          value: #@ "xcc-demo.{}".format(data.values.remote.dns.suffix)
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xcc-demo
  namespace: xcc-demo
spec:
  selector:
    app: xcc-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xcc-demo
  namespace: xcc-demo
spec:
  rules:
  - host: #@ "xcc-demo.{}".format(data.values.local.dns.suffix)
    http:
      paths:
      - backend:
          service: 
            name: xcc-demo
            port: 
              number: 8080
        path: /
        pathType: ImplementationSpecific